export const CATALOG_URL = '/[store_name]'
export const HOME = '/'
export const NOT_FOUND = '/404'
export const BASE_API_WHATSAPP = 'https://api.whatsapp.com'
export const CHECKOUT = '/[store_name]/checkout'
